---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blesta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: holdenk/blesta:latest
        volumeMounts:
        - name: apache2-config-volume
          mountPath: /etc/apache2/apache2.conf
          subPath: apache2.conf
        - name: apache2-config-volume
          mountPath: /etc/php/8.1/apache2/conf.d/custom.ini
          subPath: php.ini
        - name: apache2-config-volume
          mountPath: /var/www/html/blesta.php
          subPath: blesta.php
        ports:
        - containerPort: 80
          name: apache2
          protocol: TCP
      volumes:
        - name: apache2-config-volume
          configMap:
            name: apache2-config
            items:
            - key: apache2
              path: apache2.conf
            - key: apache2-site
              path: custom.ini
            - key: apache2-site
              path: blesta.php
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-service
spec:
  type: NodePort
  selector:
    app: apache2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: apache

